services:
  localdb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3308:3306
      - 33080:33060
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --innodb_ft_server_stopword_table=testdb/StopWord
      - --innodb_ft_min_token_size=2

    volumes:
      - ./mysql:/var/lib/mysql
