import { ThemeProvider } from '@/components/theme-provider';
import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import { use } from 'react';
import { BookMarkedIcon } from 'lucide-react';
import { auth } from '@/lib/auth';
import Nav from './Nav';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = use(auth());

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <div className='flex flex-col container justify-between mx-auto h-screen'>
              <header className='flex justify-between'>
                <Link
                  href='/'
                  className='text-3xl flex items-center tracking-tight font-bold text-green-500 no-underline'
                >
                  <BookMarkedIcon size={28} />
                  Book & Mark
                </Link>
                <Nav />
              </header>
              <main className='border flex-1'>{children}</main>
              <footer className='text-center text-green-500'>
                &#169; Indiflex SeniorCoding 2025
              </footer>
            </div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
